
package vista;

import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JTable;
import javax.swing.table.TableModel;
import modelo.Venta;

/**
 *
 * Julian David Rendon Cardona - 2177387 - julian.david.rendon@correounivalle.edu.co
 */
public class VentanaVentas extends javax.swing.JFrame {

    /**
     * Creates new form VentanaVentas
     */
    public VentanaVentas() 
    {
        initComponents();
        this.addTablaHistorialListener(new TablaHistorialListener());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        btnAgregarAnho = new javax.swing.JButton();
        btnEditarAnho = new javax.swing.JButton();
        btnEliminarAnho = new javax.swing.JButton();
        btnNuevoPronostico = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCantidadVentas = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbHistorialVentas = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbPronosticoVentas = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        txtPromVariacion = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtAnhosPronosticos = new javax.swing.JTextField();
        btnHacerPronostico = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(215, 215, 215));

        jPanel3.setBackground(new java.awt.Color(230, 230, 230));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setText("Controles");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, -1));

        btnAgregarAnho.setText("Agregar Año");
        btnAgregarAnho.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.add(btnAgregarAnho, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 110, 40));

        btnEditarAnho.setText("Editar Año");
        btnEditarAnho.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.add(btnEditarAnho, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 110, 40));

        btnEliminarAnho.setText("Eliminar Año");
        btnEliminarAnho.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.add(btnEliminarAnho, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 110, 40));

        btnNuevoPronostico.setText("Nuevo Pronostico");
        btnNuevoPronostico.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.add(btnNuevoPronostico, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 110, 40));

        jPanel2.setBackground(new java.awt.Color(230, 230, 230));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Datos de venta");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        jLabel2.setText("Cantidad de ventas:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        txtCantidadVentas.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.add(txtCantidadVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 130, 30));

        jPanel4.setBackground(new java.awt.Color(230, 230, 230));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbHistorialVentas.setModel(new javax.swing.table.DefaultTableModel(
            null,
            new String [] {
                "Año", "Ventas", "Diferencia Anual", "Variación"
            }
        ));
        jScrollPane1.setViewportView(tbHistorialVentas);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 640, 160));

        jLabel7.setText("Historial de ventas");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel5.setBackground(new java.awt.Color(230, 230, 230));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbPronosticoVentas.setModel(new javax.swing.table.DefaultTableModel(
            null,
            new String [] {
                "Año", "Prónostico Ventas"
            }
        ));
        jScrollPane2.setViewportView(tbPronosticoVentas);

        jPanel5.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 0, 300, 180));

        jLabel6.setText("Promedio de variación:");
        jPanel5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        txtPromVariacion.setEditable(false);
        jPanel5.add(txtPromVariacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 140, 30));

        jLabel8.setText("Pronóstico de ventas");
        jPanel5.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel3.setText("Años a pronosticar");
        jPanel5.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        jLabel4.setText("Cantidad:");
        jPanel5.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        txtAnhosPronosticos.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel5.add(txtAnhosPronosticos, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 140, 30));

        btnHacerPronostico.setText("Pronosticar");
        btnHacerPronostico.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel5.add(btnHacerPronostico, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 90, 40));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(12, 12, 12)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Action Listener botones
    
    public void addBtnAgregarAnhoListener(ActionListener listener)
    {
        btnAgregarAnho.addActionListener(listener);
    }
    
    public void addBtnEditarAnhoListener(ActionListener listener)
    {
        btnEditarAnho.addActionListener(listener);
    }
    
    public void addBtnEliminarAnhoListener(ActionListener listener)
    {
        btnEliminarAnho.addActionListener(listener);
    }
    
    public void addBtnNuevoPronosticoListener(ActionListener listener)
    {
        btnNuevoPronostico.addActionListener(listener);
    }
    
    public void addBtnHacerPronosticoListener(ActionListener listener)
    {
        btnHacerPronostico.addActionListener(listener);
    }
    
    //TABLAS
    
    public TableModel getModelTablaHistorial()
    {
        return tbHistorialVentas.getModel();
    }
    
    public int getFilaSeleccionadaTablaHistorial()
    {
        return tbHistorialVentas.getSelectedRow();
    }
    
    public TableModel getModelTablaPronostico()
    {
        return tbPronosticoVentas.getModel();
    }
    
    public int getFilaSeleccionadaTablaPronostico()
    {
        return tbPronosticoVentas.getSelectedRow();
    }
    
    //SETTERS Y GETTERS
    
    public String getTxtCantidadVentas()
    {
        return txtCantidadVentas.getText();
    }
    
    public String getTxtAnhosProsnoticos()
    {
        return txtAnhosPronosticos.getText();
    }
    
    public String getTxtPromVariacion()
    {
        return txtPromVariacion.getText();
    }
    
    public void setTxtCantidadVentas(String txt)
    {
        txtCantidadVentas.setText(txt);
    }
    
    public void setTxtAnhosPronosticos(String txt)
    {
        txtAnhosPronosticos.setText(txt);
    }
    
    public void setTxtPromVariacion(String txt)
    {
        txtPromVariacion.setText(txt);
    }
    
    public void vaciarTxtVentas()
    {
        txtCantidadVentas.setText("");
    }

    //LISTENER TABLAS
    
    public void addTablaHistorialListener(MouseAdapter listener)
    {
        tbHistorialVentas.addMouseListener(listener);
    }
    
    class TablaHistorialListener extends MouseAdapter
    {
        public void mouseClicked(MouseEvent e)
        {
            JTable tabla = (JTable)e.getSource();
            int fila = tabla.getSelectedRow();
            if(fila == -1)
            {
                setTxtCantidadVentas("");
            }
            else
            {
                setTxtCantidadVentas(String.valueOf(tabla.getValueAt(fila, 1)));
            }
        }
    }
    
    
    /**
     * 
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaVentas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarAnho;
    private javax.swing.JButton btnEditarAnho;
    private javax.swing.JButton btnEliminarAnho;
    private javax.swing.JButton btnHacerPronostico;
    private javax.swing.JButton btnNuevoPronostico;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JTable tbHistorialVentas;
    public javax.swing.JTable tbPronosticoVentas;
    private javax.swing.JTextField txtAnhosPronosticos;
    private javax.swing.JTextField txtCantidadVentas;
    private javax.swing.JTextField txtPromVariacion;
    // End of variables declaration//GEN-END:variables
}
